# Generated by Django 5.2.7 on 2025-10-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='orginal_link',
            new_name='original_link',
        ),
    ]
