# Generated by Django 5.2.7 on 2025-10-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_rename_orginal_link_shorturl_original_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='images/shortQR/'),
        ),
    ]
