# Generated by Django 5.2.7 on 2025-10-25 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_shorturl_custom_short_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QRCodes',
            new_name='QRCode',
        ),
    ]
