# Generated by Django 5.2.7 on 2025-10-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_rename_qrcodes_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='images/QRcodes/'),
        ),
    ]
